### ISSUE TITLE
API keys are visible to the public

### ISSUE THREAD

**Issue by andykr1k** [MarcusHsieh/algorithm-avengers#5]
I recommend removing the static api key and replacing it with either a github secret or a secret that is exposed through your hosting platform.

Found in src/app/api/keys/route.ts

**Comment by MarcusHsieh** [comment]
Hi Andrew, thanks for the tip. I'll look into a fix soon.

**Comment by andykr1k** [comment]
I recommend putting keys in a .env file and then using a .gitignore to ignore that file from being pushed to github.

**Comment by MarcusHsieh** [comment]
That did the trick!

**Comment by andykr1k** [comment]
Awesome! Good work bro.
